### ISSUE TITLE
Make the webhook server a system service that will start on boot and handle restarts

### ISSUE THREAD

**Issue by JackWilb** [multinet-app/multinet-deploy#8]

**Comment by waxlamp** [comment]
Let's hold off on this, and other changes to the `multinet-deploy` repository, for now. I'm working with a couple of devops experts at Kitware to see if there's a simpler way to accomplish a deployment strategy.

**Comment by waxlamp** [comment]
This is no longer necessary now that we've moved to an Ansible-based deployment strategy.
